export const content = [
  {
    category: "action",
    title: "Action movies to you",
    movies: [
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
    ],
  },
  {
    category: "comedy",
    title: "Best comedy picks for you",
    movies: [
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
    ],
  },
  {
    priority: 0,
    category: "drama",
    title: "Best TV drama for you",
    movies: [
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
    ],
  },
  {
    priority: 1,
    category: "romance",
    title: "Best romatic shows for you",
    movies: [
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
    ],
  },
  {
    priority: 2,
    category: "disney",
    title: "Popular Disney movies for you",
    movies: [
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
      { img: "src/img/dummy-movie-image.png", url: "#" },
    ],
  },
];
